---
- name: Copy custom alias to $HOME/.{{custom_name}}
  copy:
    src: custom
    dest: $HOME/.{{custom_name}}

- name: Add source $HOME/.{{custom_name}} to ~/.zshrc configuration
  lineinfile:
    path: $HOME/.zshrc
    regexp: '^source \$HOME\/.{{custom_name}}'
    insertafter: '^# alias ohmyzsh="mate ~/.oh-my-zsh"'
    line: 'source $HOME/.{{custom_name}}'
