os:
  - linux
services:
  - docker
before_install:
  - docker version
install:
  - docker build -q -t ansible:test .
  - docker images
  - docker run --name containertest -d -w /home/jhipster/app/playbooks/ ansible:test
script:
  - docker exec -it containertest ansible --version
  # tools
  - docker exec -it containertest ansible-playbook tools.yml -e ansible_become_pass=jhipster
  - docker exec -it containertest vim --version
  - docker exec -it containertest curl --version
  - docker exec -it containertest wget --version
  # git
  - docker exec -it containertest ansible-playbook git.yml -e ansible_become_pass=jhipster -e 'git_username="Firstname Lastname"' -e git_email=yourmail@localhost
  - docker exec -it containertest git version
  # zsh
  - docker exec -it containertest ansible-playbook zsh.yml -e ansible_become_pass=jhipster
  - docker exec -it containertest zsh --version
  # openjdk8
  - docker exec -it containertest ansible-playbook openjdk8.yml -e ansible_become_pass=jhipster
  - docker exec -it containertest java -version
  # NodeJS
  - docker exec -it containertest ansible-playbook node.yml -e ansible_become_pass=jhipster -e node_version=8.11.1
  - docker exec -it containertest node -v
  - docker exec -it containertest npm -v
  # Yarn
  - docker exec -it containertest ansible-playbook yarn.yml -e ansible_become_pass=jhipster -e node_version=8.11.1
  - docker exec -it containertest yarn -v
  # docker
  - docker exec -it containertest ansible-playbook docker.yml -e ansible_become_pass=jhipster
  - docker exec -it containertest docker -v
  # docker-compose
  - docker exec -it containertest ansible-playbook dockercompose.yml -e ansible_become_pass=jhipster
  - docker exec -it containertest docker-compose version
