os:
  - linux
services:
  - docker
before_install:
  - docker version
install:
  - docker build -t ansible:test .
  - docker images
  - docker run --name containertest -d ansible:test
script:
  - docker exec -it containertest ansible --version
  # tools
  - docker exec -it containertest ansible-playbook -v tools.yml -e ansible_become_pass=jhipster
  - docker exec -it containertest vim --version
  - docker exec -it containertest curl --version
  - docker exec -it containertest wget --version
  # openjdk8
  - docker exec -it containertest ansible-playbook -v openjdk8.yml -e ansible_become_pass=jhipster
  - docker exec -it containertest java -version
