---
- name: Add repository ppa:webupd8team/terminix
  become: true
  apt_repository:
    repo: 'ppa:webupd8team/terminix'
    state: present

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist

- name: Install tilix
  become: true
  apt:
    name: tilix
    state: present

- name: Create symlink for vte.sh
  become: true
  file:
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh
    state: link
