---
- name: Add repository ppa:git-core/ppa
  become: true
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist

- name: Install git
  become: true
  apt:
    name: git
    state: present
  with_items: "git"

- name: Config git user.name={{username}}
  shell: git config --global user.name "{{username}}"
  when: username is defined

- name: Config git user.email={{email}}
  shell: git config --global user.email "{{email}}"
  when: email is defined
