---
- name: Install vim
  become: true
  apt:
    name: vim
    state: present
  with_items: "vim"

- name: Install curl
  become: true
  apt:
    name: curl
    state: present
  with_items: "curl"

- name: Install wget
  become: true
  apt:
    name: wget
    state: present
  with_items: "wget"
